type: object
properties:
  events:
    type: array
    items:
      type: object
      properties:
        action:
          type: string
          description: Event type
        event_id:
          type: string
          description: Unique event identifier
        event_datetime:
          type: string
          description: Event datetime
        author:
          type: string
          description: Author of the event
        author_type:
          type: string
          description: Type of the author "ui" or "api"
        pim_source:
          type: string
          description: URL of the PIM that sends the event
        data:
          type: object
          properties:
            code:
              type: string
              description: Product model code
