type: object
required: ["uuid", "code", "labels", "enabled", "steps"]
properties:
  uuid:
    type: string
    description: Workflow UUID
  code:
    type: string
    description: Workflow code
  labels:
    type: object
    description: Workflow labels per locale
    additionalProperties:
      type: string
  enabled:
    type: boolean
    description: Whether the workflow is enabled
  steps:
    type: array
    description: List of workflow steps
    items:
      type: object
      required: ["uuid", "code", "type", "labels", "descriptions", "allotted_time"]
      properties:
        uuid:
          type: string
          description: Step UUID
        code:
          type: string
          description: Step code
        type:
          type: string
          description: Step type (e.g. enrichment, review)
        labels:
          type: object
          description: Step labels per locale
          additionalProperties:
            type: string
        descriptions:
          type: object
          description: Step descriptions per locale
          additionalProperties:
            type: string
        allotted_time:
          type: object
          description: 'Allotted time for the step (e.g. `{"value": 1, "unit": "days"}` or nullable)'
          required: ["value", "unit"]
          properties:
            value:
              type: integer
              description: Amount of time
            unit:
              type: string
              description: Time unit (days)
          x-nullable: true

example:
  uuid: "6f37476a-04c2-46c0-b6d0-e18316959068"
  code: "enrichment_workflow"
  labels:
    en_US: "Enrichment workflow"
    fr_FR: "Workflow d'enrichissement"
  enabled: true
  steps:
    - uuid: "f626d0e5-84a5-41fc-8215-65508c253edb"
      code: "marketing_enrichment"
      type: "enrichment"
      labels:
        en_US: "Marketing enrichment"
        fr_FR: "Enrichissement marketing"
      descriptions:
        en_US: "Enrich marketing attributes"
      allotted_time:
        value: 3
        unit: "days"
    - uuid: "b2c1f3d4-5e6a-4c8b-9f0e-2d3e4f5a6b7c"
      code: "marketing_review"
      type: "review"
      labels: {}
      descriptions: {}
      allotted_time: null
