var gulp = require('gulp');
var webserver = require('gulp-webserver');
var del = require('del');

var requireDir = require('require-dir');
var tasks = requireDir('./tasks');

// Clean dist directory
gulp.task('clean-dist', function () {
  return del(['dist/*', 'tmp/*']);
});

// Watch if markdown, less, html or image files have changed
// so as to relaunch the build into dist directory
// Should be used for dev purpose
//
// A watched change re-runs 'create-dist', which starts by wiping dist/tmp
// ('clean-dist'). gulp.watch(glob, ['create-dist']) calls orchestrator's start()
// directly on every change event; if a second change fires before the first
// rebuild finishes (e.g. an editor that writes a file twice per save), orchestrator
// resets 'clean-dist' and re-queues it into the still-running sequence, wiping
// dist/tmp out from under a stream from the first run that's still writing into it
// (ENOENT on dist/**/*.html). This guard makes sure only one 'create-dist' run is
// ever in flight, queuing at most one rerun for changes that land mid-build.
var rebuildRunning = false;
var rebuildQueued = false;

function rebuild() {
  if (rebuildRunning) {
    rebuildQueued = true;
    return;
  }
  rebuildRunning = true;
  gulp.start('create-dist');
}

gulp.on('task_stop', function (e) {
  if (e.task === 'create-dist') {
    rebuildRunning = false;
    if (rebuildQueued) {
      rebuildQueued = false;
      rebuild();
    }
  }
});

gulp.task('watch', ['create-dist'], function() {
  // available-events.md is generated by 'fetch-remote-events' on every build, not
  // hand-edited — watching it would make every rebuild retrigger itself forever.
  gulp.watch(['content/**/*.md', '!content/event-platform/available-events.md'], rebuild);
  gulp.watch('content/img/**/*', rebuild);
  gulp.watch('content/swagger/**/*.yaml', rebuild);
  gulp.watch('content/beta/**/*.yaml', rebuild);
  gulp.watch('styles/**/*.less', rebuild);
  gulp.watch('src/**/*.handlebars', rebuild);
});

// Launch a server with dist directory exposed on it
// Should be used for dev purpose
gulp.task('launch-webserver', ['create-dist'], function() {
  return gulp.src('dist')
    .pipe(webserver({
      host: '0.0.0.0',
      livereload: true,
      directoryListing: false,
      open: true
    }));
});

// Build the documentation is dist directory
gulp.task('create-dist', [
  'clean-dist',
  'less',
  'copy-assets',
  'reference',
  'reference-paas',
  'landings',
  'build-concepts',
  'build-rest-api',
  'build-graphql',
  'build-supplier-data-manager',
  'build-event-platform',
  'build-events-api',
  'build-extensions',
  'build-advanced-extensions',
  'build-php-client',
  'build-misc-documentation',
  'build-guides',
  'build-getting-started',
  'build-events-reference-page',
  'build-app-developer-tools',
  'build-apps',
  'build-app-portal',
  'build-tutorials-homepage',
  'build-tutorials',
  'build-news',
  'build-redirections',
  'build-px-insights',
  'build-mcp',
  'build-extension-platform',
]);

// Main task that should be used for development purpose
gulp.task('serve', [
  'launch-webserver',
  'watch'
]);
