type: object
properties:
  uuid:
    type: string
    description: Product uuid
  enabled:
    type: boolean
    description: Whether the product is enabled
    default: true
  family:
    type: string
    description: <a href='api-reference.html#Family'>Family</a> code from which the product inherits its attributes and attributes requirements.
    x-validation-rules: It is equal to an existing family code. In the case of variant product, the given family should be the same as the product model family.
    default: "null only in the case of a non variant product"
  categories:
    type: array
    description: Codes of the <a href='api-reference.html#Category'>categories</a> in which the product is classified
    x-validation-rules: Each string of the array is equal to an existing category code
    items:
      type: string
    default: []
  groups:
    type: array
    description: Codes of the groups to which the product belong
    x-validation-rules: Each string of the array is equal to an existing group code
    items:
      type: string
    default: []
  parent:
    type: string
    description: Code of the parent <a href='api-reference.html#Productmodel'>product model</a> when the product is a variant (only available since the 2.0). This parent can be modified since the 2.3.
    x-validation-rules: It is equal to an existing product model code only if the product is variant otherwise it's equal to null
    default: "null"
    x-from-version: '2.0'
  values:
    type: object
    description: "Product attributes values, see <a href='/concepts/products.html#focus-on-the-product-values'>Product values</a> section for more details"
    x-validation-rules: Validation rules detailed in Product values section
    properties:
      attributeCode:
        type: array
        items:
          type: object
          properties:
            scope:
              type: string
              description: <a href='api-reference.html#Channel'>Channel</a> code of the product value
            locale:
              type: string
              description: <a href='api-reference.html#Locale'>Locale</a> code of the product value
            data:
              type: object
              description: Product value. See <a href='/concepts/products.html#the-data-format'>the `data` format</a> section for more details.
            linked_data:
              type: object
              x-read-only: true
              description: Object containing labels of attribute options (only available since the 5.0 and when query parameter "with_attribute_options" is set to "true"). See <a href='/concepts/products.html#the-linked_data-format'>the `linked_data` format</a> section for more details.
              x-from-version: '5.0'
              properties:
                attribute:
                  type: string
                code:
                  type: string
                labels:
                  type: object
  associations:
    type: object
    description: Several associations related to groups, product models and/or other products, grouped by association types
    x-validation-rules: "&bull; The `associationTypeCode` is the code of an existing association type. &#10;&bull; Each string in the array of the property `groups` is the code of an existing group. &#10;&bull; Each string in the array of the property `products` is the uuid of an existing product. &#10;&bull; Each string in the array of the property `product_models` is the code of an existing product model."
    properties:
      associationTypeCode:
        type: object
        properties:
          groups:
            type: array
            description: Array of groups codes with which the product is in relation
            items:
              type: string
          products:
            type: array
            description: Array of product uuids with which the product is in relation
            items:
              type: string
          product_models:
            type: array
            description: Array of product model codes with which the product is in relation (only available since the v2.1)
            x-from-version: '2.1'
            items:
              type: string
  quantified_associations:
    type: object
    description: Several quantified associations related to products and/or product models, grouped by quantified association types (only available since the 5.0)
    x-validation-rules: "&bull; The `quantifiedAssociationTypeCode` is the code of an existing association type which provides quantity information. &#10;&bull; Each object in the array of the property `products` contains the uuid of an existing product and the quantity of it."
    x-from-version: '5.0'
    properties:
      quantifiedAssociationTypeCode:
        type: object
        properties:
          products:
            type: array
            description: Array of objects containing product uuids and quantities with which the product is in relation
            items:
              type: object
              properties:
                uuid:
                  type: string
                quantity:
                  type: integer
          product_models:
            type: array
            description: Array of objects containing product model codes and quantities with which the product is in relation
            items:
              type: object
              properties:
                code:
                  type: string
                quantity:
                  type: integer
  created:
    type: string
    description: Date of creation
    format: dateTime
    x-immutable: true
    x-read-only: true
  updated:
    type: string
    description: Date of the last update
    format: dateTime
    x-read-only: true
  metadata:
    type: object
    description: More information around the product (only available since the v2.0 in the Enterprise Edition)
    x-immutable: true
    x-read-only: true
    x-from-version: '2.0'
    properties:
      workflow_status:
        description: Status of the product regarding the user permissions
        type: string
        enum: ['read_only','draft_in_progress','proposal_waiting_for_approval','working_copy']
  quality_scores:
    type: object
    description: Product quality scores for each channel/locale combination (only available since the 5.0 and when the "with_quality_scores" query parameter is set to "true")
    x-immutable: true
    x-read-only: true
    x-from-version: '5.0'
  completenesses:
    type: array
    description: Product completenesses for each channel/locale combination (only available since the 7.0 version, and when the "with_completenesses" query parameter is set to "true")
    x-immutable: true
    x-read-only: true
    x-from-version: '7.0'
    items:
      type: object
      properties:
        scope:
          type: string
        locale:
          type: string
        data:
          type: integer

example: {
  "uuid": "25566245-55c3-42ce-86d9-8610ac459fa8",
  "enabled": true,
  "family": "tshirt",
  "categories": ["summer_collection"],
  "groups": [],
  "parent": null,
  "values": {
    "sku": [
      {
        "data": "top",
        "locale": null,
        "scope": null
      }
    ],
    "name": [
      {
        "data": "Top",
        "locale": "en_US",
        "scope": null
      },
      {
        "data": "Débardeur",
        "locale": "fr_FR",
        "scope": null
      }
    ],
    "description": [
      {
        "data": "Summer top",
        "locale": "en_US",
        "scope": "ecommerce"
      },
      {
        "data": "Top",
        "locale": "en_US",
        "scope": "tablet"
      },
      {
        "data": "Débardeur pour l'été",
        "locale": "fr_FR",
        "scope": "ecommerce"
      },
      {
        "data": "Débardeur",
        "locale": "fr_FR",
        "scope": "tablet"
      }
    ],
    "price": [
      {
        "locale": null,
        "scope": null,
        "data": [
          {
            "amount": "15.5", "currency": "EUR"
          },
          {
            "amount": "15", "currency": "USD"
          }
        ]
      }
    ],
    "color": [
      {
        "locale": null,
        "scope": null,
        "data": "black",
        "linked_data": {
          "attribute": "color",
          "code": "black",
          "labels": {
            "en_US": "Black",
            "fr_FR": "Noir"
          }
        }
      }
    ],
    "size": [
      {
        "locale": null,
        "scope": null,
        "data": "m",
        "linked_data": {
          "attribute": "size",
          "code": "m",
          "labels": {
            "en_US": "M",
            "fr_FR": "M"
          }
        }
      }
    ],
    "collection": [
      {
        "locale": null,
        "scope": null,
        "data": [
          "winter_2016"
        ],
        "linked_data": {
          "winter_2016": {
            "attribute": "collection",
            "code": "winter_2016",
            "labels": {
              "en_US": "Winter 2016",
              "fr_FR": "Hiver 2016"
            }
          }
        }
      }
    ]
  },
  "created": "2016-06-23T18:24:44+02:00",
  "updated": "2016-06-25T17:56:12+02:00",
  "associations": {
    "PACK": {
      "products": ["d055527c-0698-4967-8f16-8a5f23f4e5cf"],
      "product_models": [],
      "groups": []
    }
  },
  "quantified_associations": {
    "PRODUCT_SET": {
      "products": [
        {
          "uuid": "fc24e6c3-933c-4a93-8a81-e5c703d134d5",
          "quantity": 2
        },
        {
          "uuid": "a9b69002-a0b1-4ead-85c2-f8dbf59c6cfc",
          "quantity": 1
        }
      ],
      "product_models": [
        {
          "identifier": "model-biker-jacket-leather",
          "quantity": 2
        }
      ]
    }
  },
  "quality_scores": [
    {
      "scope": "ecommerce",
      "locale": "en_US",
      "data": "A"
    },
    {
      "scope": "ecommerce",
      "locale": "fr_FR",
      "data": "B"
    },
    {
      "scope": "tablet",
      "locale": "en_US",
      "data": "D"
    },
    {
      "scope": "tablet",
      "locale": "fr_FR",
      "data": "E"
    }
  ],
  "completenesses": [
    {
      "scope": "ecommerce",
      "locale": "en_US",
      "data": 10
    },
    {
      "scope": "ecommerce",
      "locale": "fr_FR",
      "data": 20
    },
    {
      "scope": "tablet",
      "locale": "en_US",
      "data": 30
    },
    {
      "scope": "tablet",
      "locale": "fr_FR",
      "data": 40
    }
  ]
}
