post:
  summary: Submit a draft for approval
  operationId: "post_product_model_proposal"
  tags:
    - Product model
  x-versions:
    - "2.3"
    - "3.x"
    - "4.0"
    - "5.0"
    - "6.0"
    - "SaaS"
  x-ee: true
  description: This endpoint allows you to submit a product model draft for approval.
  parameters:
    - $ref: '#/parameters/code'
  responses:
    201:
      $ref: "#/responses/Submitted"
    401:
      $ref: "#/responses/401Error"
    403:
      $ref: "#/responses/403Error"
    415:
      $ref: "#/responses/415Error"
    422:
      $ref: "#/responses/422Error"
