pagination_type:
  name: pagination_type
  in: query
  description: Pagination method type, see <a href="/documentation/pagination.html">Pagination</a> section
  required: false
  type: string
  default: "page"
  x-validation-rules: One of the following values
  enum: ["page", "search_after"]
page:
  name: page
  in: query
  description: Number of the page to retrieve when using the `page` pagination method type. <strong>Should never be set manually</strong>, see <a href="/documentation/pagination.html#pagination">Pagination</a> section
  required: false
  type: integer
  default: 1
search_after:
  name: search_after
  in: query
  description: Cursor when using the `search_after` pagination method type. <strong>Should never be set manually</strong>, see <a href="/documentation/pagination.html">Pagination</a> section
  required: false
  type: string
  default: "cursor to the first page"
limit:
  name: limit
  in: query
  description: Number of results by page, see <a href="/documentation/pagination.html">Pagination</a> section
  required: false
  type: integer
  minimum: 1
  maximum: 100
  default: 10
code:
  name: code
  in: path
  description: Code of the resource
  required: true
  type: string
uuid:
  name: uuid
  in: path
  description: Uuid of the resource
  required: true
  type: string
reference_entity_code:
  name: reference_entity_code
  in: path
  description: Code of the reference entity
  required: true
  type: string
asset_family_code:
  name: asset_family_code
  in: path
  description: Code of the asset family
  required: true
  type: string
attribute_code:
  name: attribute_code
  in: path
  description: Code of the attribute
  required: true
  type: string
asset_code:
  name: asset_code
  in: path
  description: Code of the asset
  required: true
  type: string
channel_code:
  name: channel_code
  in: path
  description: Code of the channel
  required: true
  type: string
locale_code:
  name: locale_code
  in: path
  description: Code of the locale if the asset is localizable or equal to `no-locale` if the asset is not localizable
  required: true
  type: string
family_code:
  name: family_code
  in: path
  description: Code of the family
  required: true
  type: string
with_count:
  name: with_count
  in: query
  description: Return the count of items in the response. Be carefull with that, on a big catalog, it can decrease performance in a significative way
  default: false
  type: boolean
  required: false
with_attribute_options:
  name: with_attribute_options
  in: query
  description: Return labels of attribute options in the response. (Only available since the 5.0 version)
  default: false
  type: boolean
  required: false
  x-from-version: "5.0"
with_table_select_options:
  name: with_table_select_options
  in: query
  description: Return the options of 'select' column types (of a table attribute) in the response. (Only available since the 7.0 version)
  default: false
  type: boolean
  required: false
  x-from-version: "7.0"
with_quality_scores__products:
  name: with_quality_scores
  in: query
  description: Return product quality scores in the response. (Only available since the 5.0 version)
  default: false
  type: boolean
  required: false
  x-from-version: "5.0"
with_quality_scores__product_models:
  name: with_quality_scores
  in: query
  description: Return product model quality scores in the response. <strong>(Only available since the 6.0 version)</strong>
  type: boolean
  required: false
  x-from-version: "6.0"
with_completenesses:
  name: with_completenesses
  in: query
  description: Return product completenesses in the response. (Only available since the 6.0 version)
  default: false
  type: boolean
  required: false
  x-from-version: "6.0"
with_position:
  name: with_position
  in: query
  description: Return information about category position into its category tree (only available since the 7.0 version)
  required: false
  type: boolean
  x-from-version: "7.0"
updated_before:
  name: updated_before
  in: query
  description: Filter products that have been updated BEFORE the provided date (Only available on Catalogs endpoints)
  type: string
  format: date
  required: false
  x-from-version: "SaaS"
updated_after:
  name: updated_after
  in: query
  description: Filter products that have been updated AFTER the provided date (Only available on Catalogs endpoints)
  type: string
  format: date
  required: false
  x-from-version: "SaaS"
with_enriched_attributes:
  name: with_enriched_attributes
  in: query
  description: Return attribute values of the category (only available on SaaS platforms)
  required: false
  type: boolean
  x-from-version: "SaaS"
with_enriched_attributes_coming_soon:
  name: with_enriched_attributes
  in: query
  description: Return attribute values of the category (only available on SaaS platforms) <strong>[COMING SOON]<strong>
  required: false
  type: boolean
  x-from-version: "SaaS"
