type: object
required: ["identifier"]
properties:
  identifier:
    type: string
    description: Product identifier, i.e. the value of the only `pim_catalog_identifier` attribute
  enabled:
    type: boolean
    description: Whether the product is enable
    default: true
  family:
    type: string
    description: Family code from which the product inherits its attributes and attributes requirements
    x-validation-rules: It is equal to an existing family code. In the case of variant product, the given family should be the same as the product model family.
    default: "null only in the case of a non variant product"
  categories:
    type: array
    description: Codes of the categories in which the product is classified
    x-validation-rules: Each string of the array is equal to an existing category code
    items:
      type: string
    default: []
  groups:
    type: array
    description: Codes of the groups to which the product belong
    x-validation-rules: Each string of the array is equal to an existing group code
    items:
      type: string
    default: []
  parent:
    type: string
    description: Code of the parent product model when the product is a variant (only available since the 2.0). This parent can be modified since the 2.3.
    x-validation-rules: It is equal to an existing product model code only if the product is variant otherwise it's equal to null
    default: "null"
  values:
    type: object
    description: "Product attributes values, see <a href='/concepts/products.html#focus-on-the-products-values'>Product values</a> section for more details"
    x-validation-rules: Validation rules detailed in Product values section
    properties:
      attributeCode:
        type: array
        items:
          type: object
          properties:
            scope:
              type: string
              description: Channel code of the product value
            locale:
              type: string
              description: Locale code of the product value
            data:
              type: object
              description: Product value
  associations:
    type: object
    description: Several associations related to groups and/or other products, grouped by association types
    x-validation-rules: "&bull; The `associationTypeCode` is the code of an existing association type. &#10;&bull; Each string in the array of the property `groups` is the code of an existing group. &#10;&bull; Each string in the array of the property `products` is the identifier of an existing product. &#10;&bull; Identifiers used in the array of the property `products` cannot be equal to the product identifier."
    properties:
      associationTypeCode:
        type: object
        properties:
          groups:
            type: array
            description: Array of groups codes with which the product is in relation
            items:
              type: string
          products:
            type: array
            description: Array of product identifiers with which the product is in relation
            items:
              type: string
          product_models:
            type: array
            description: Array of product model codes with which the product is in relation (only available since the v2.1)
            items:
              type: string
  quantified_associations:
    type: object
    description: Several quantified associations related to products and/or product models, grouped by quantified association types (only available in SaaS and sincce the v5.0)
    x-validation-rules: "&bull; The `quantifiedAssociationTypeCode` is the code of an existing association type which provides quantity information. &#10;&bull; Each object in the array of the property `products` contains the identifier of an existing product and the quantity of it. &#10;&bull; Each object in the array of the property `product_models` contains the code of an existing product model and the quantity of it. &#10;&bull; Identifiers used in the object collection of the property `products` cannot be equal to the product identifier."
    properties:
      quantifiedAssociationTypeCode:
        type: object
        properties:
          products:
            type: array
            description: Array of objects containing product identifiers and quantities with which the product is in relation
            items:
              type: object
              properties:
                identifier:
                  type: string
                quantity:
                  type: string
          product_models:
            type: array
            description: Array of objects containing product model codes and quantities with which the product is in relation
            items:
              type: object
              properties:
                identifier:
                  type: string
                quantity:
                  type: string
  created:
    type: string
    description: Date of creation
    format: dateTime
    x-immutable: true
    x-read-only: true
  updated:
    type: string
    description: Date of the last update
    format: dateTime
    x-read-only: true
  metadata:
    type: object
    description: More information around the product (only available since the v2.0 in the Enterprise Edition)
    x-immutable: true
    x-read-only: true
    properties:
      workflow_status:
        description: Status of the product regarding the user permissions (only available since the v2.0 in the Enterprise Edition)
        type: string
        enum: ['read_only','draft_in_progress','proposal_waiting_for_approval','working_copy']
    
example: {
  "identifier": "top",
  "enabled": true,
  "family": "tshirt",
  "categories": ["summer_collection"],
  "groups": [],
  "parent": null,
  "values": {
    "name": [
      {
        "data": "Top",
        "locale": "en_US",
        "scope": null,
      },
      {
        "data": "Débardeur",
        "locale": "fr_FR",
        "scope": null,
      }
    ],
    "description": [
      {
        "data": "Summer top",
        "locale": "en_US",
        "scope": "ecommerce"
      },
      {
        "data": "Top",
        "locale": "en_US",
        "scope": "tablet"
      },
      {
        "data": "Débardeur pour l'été",
        "locale": "fr_FR",
        "scope": "ecommerce"
      },
      {
        "data": "Débardeur",
        "locale": "fr_FR",
        "scope": "tablet"
      }
    ],
    "price": [
      {
        "locale": null,
        "scope": null,
        "data": [
          {
            "amount": "15.5", "currency": "EUR"
          },
          {
            "amount": "15", "currency": "USD"
          }
        ]
      }
    ],
    "color": [
      {
        "locale": null,
        "scope": null,
        "data": "black"
      }
    ],
    "size": [
      {
        "locale": null,
        "scope": null,
        "data": "m"
      }
    ]
  },
  "created": "2016-06-23T18:24:44+02:00",
  "updated": "2016-06-25T17:56:12+02:00",
  "associations": {
    "PACK": {
      "products": ["sunglass"],
      "groups": []
    }
  },
  "quantified_associations": {
    "PACK": {
      "products": [
      {
        "identifier": "cap",
        "quantity": 2
      },
      {
        "identifier": "shoes",
        "quantity": 1
      }
      ],
      "product_models": [
      {
        "identifier": "model-biker-jacket-leather",
        "quantity": 2
      }
      ]
    },
    "PROMO": {
      "products": [],
      "product_models": []
    }
  }
}
