post:
  summary: Submit a draft for approval
  operationId: "post_proposal"
  tags:
    - Product
  x-versions:
    - "2.0"
    - "2.1"
    - "2.2"
    - "2.3"
    - "3.0"
    - "3.1"
    - "3.2"
    - "4.0"
  x-ee: true
  description: This endpoint allows you to submit a draft for approval.
  parameters:
    - $ref: '#/parameters/code'
  responses:
    201:
      $ref: "#/responses/Submitted"
    401:
      $ref: "#/responses/401Error"
    403:
      $ref: "#/responses/403Error"
    415:
      $ref: "#/responses/415Error"
    422:
      $ref: "#/responses/422Error"
