search_after:
  name: search_after
  in: query
  description: Cursor when using the `search_after` pagination method type. <strong>Should never be set manually</strong>, see <a href="/documentation/pagination.html">Pagination</a> section
  required: false
  type: string
  default: "cursor to the first page"
code:
  name: code
  in: path
  description: Code of the resource
  required: true
  type: string
attribute_code:
  name: attribute_code
  in: path
  description: Code of the attribute
  required: true
  type: string
asset_family_code:
  name: asset_family_code
  in: path
  description: Code of the asset family
  required: true
  type: string
