swagger: '2.0'
info:
  title: Akeneo PIM API
  version: "1.0.0"
# the domain of the service
host: demo.akeneo.com
# array of all schemes that your API supports
schemes:
  - http
produces:
  - application/json
paths:
  $ref: ./paths.yaml
definitions:
  $ref: ./definitions.yaml
responses:
  $ref: ./responses.yaml
parameters:
  $ref: ./parameters.yaml
