type: object
required: ["code", "family_variant"]
properties:
  code:
    type: string
    description: Product model code
    x-immutable: true
  family:
    type: string
    description: <a href='api-reference-paas.html#Family'>Family</a> code  from which the product inherits its attributes and attributes requirements (since the 3.2)
    x-validation-rules: It is equal to an existing family code
    x-immutable: true
    x-from-version: "3.2"
  family_variant:
    type: string
    description: Family variant code from which the product model inherits its attributes and variant attributes
    x-validation-rules: It is equal to an existing family variant code that belong to the family given in the `family` field
    x-immutable: true
  parent:
    type: string
    description: Code of the parent <a href='api-reference-paas.html#Productmodel'>product model</a>. This parent can be modified since the 2.3.
    x-validation-rules: "&bull; It is equal to an existing product model code&#10;&bull; This product model has the same family variant as the one given in the `family_variant field`"
    default: "null"
    x-from-version: "2.3"
  categories:
    type: array
    description: Codes of the <a href='api-reference-paas.html#Category'>categories</a> in which the product model is categorized
    x-validation-rules: Each string of the array is equal to an existing category code
    items:
      type: string
    default: []
  values:
    type: object
    description: "Product model attributes values, see <a href='/concepts/products.html#focus-on-the-product-values'>Product values</a> section for more details"
    x-validation-rules: Validation rules detailed in Product values section
    additionalProperties:
      type: array
      items:
        type: object
        properties:
          scope:
            type: string
            description: <a href='api-reference-paas.html#Channel'>Channel</a> code of the product value
          locale:
            type: string
            description: <a href='api-reference-paas.html#Locale'>Locale</a> code of the product value
          data:
            type: object
            description: <a href='api-reference-paas.html#Productuuid'>Product</a> value
          linked_data:
            type: object
            x-read-only: true
            description: Object containing additional data when a related query parameter is enabled. See <a href='/concepts/products.html#the-linked_data-format'>the `linked_data` format</a> section for more details. (only available since the 5.0)
            x-from-version: 'SaaS'
            properties:
              attribute:
                type: string
              code:
                type: string
              labels:
                type: object
  associations:
    type: object
    description: Several associations related to groups, product and/or other product models, grouped by association types
    x-validation-rules: "&bull; The `associationTypeCode` is the code of an existing association type. &#10;&bull; Each string in the array of the property `groups` is the code of an existing group. &#10;&bull; Each string in the array of the property `products` is the identifier of an existing product. &#10;&bull; Each string in the array of the property `product_models` is the code of an existing product model."
    properties:
      associationTypeCode:
        type: object
        properties:
          groups:
            type: array
            description: Array of groups codes with which the product is in relation
            items:
              type: string
          products:
            type: array
            description: Array of product identifiers with which the product is in relation
            items:
              type: string
          product_models:
            type: array
            description: Array of product model codes with which the product is in relation (only available since the v2.1)
            x-from-version: "2.1"
            items:
              type: string
  quantified_associations:
    type: object
    description: Several quantified associations related to products and/or product models, grouped by quantified association types (only available since the 5.0)
    x-validation-rules: "&bull; The `quantifiedAssociationTypeCode` is the code of an existing association type which provides quantity information. &#10;&bull; Each object in the array of the property `products` contains the identifier of an existing product and the quantity of it. &#10;&bull; Each object in the array of the property `product_models` contains the code of an existing product model and the quantity of it."
    x-from-version: "5.0"
    properties:
      quantifiedAssociationTypeCode:
        type: object
        properties:
          products:
            type: array
            description: Array of objects containing product identifiers and quantities with which the product model is in relation
            items:
              type: object
              properties:
                identifier:
                  type: string
                quantity:
                  type: integer
          product_models:
            type: array
            description: Array of objects containing product model codes and quantities with which the product model is in relation
            items:
              type: object
              properties:
                code:
                  type: string
                quantity:
                  type: integer
  created:
    type: string
    description: Date of creation
    format: dateTime
    x-immutable: true
    x-read-only: true
  updated:
    type: string
    description: Date of the last update
    format: dateTime
    x-read-only: true
  metadata:
    type: object
    description: More information around the product model (only available since the v2.3 in the Enterprise Edition)
    x-immutable: true
    x-read-only: true
    x-from-version: "2.3"
    properties:
      workflow_status:
        description: Status of the product model regarding the user permissions
        type: string
        enum: ['read_only','draft_in_progress','proposal_waiting_for_approval','working_copy']
  quality_scores:
    type: object
    description: Product model quality scores for each channel/locale combination (<strong>only available since the 7.0 version</strong> and when the "with_quality_scores" query parameter is set to "true")
    x-immutable: true
    x-read-only: true
    x-from-version: "7.0"
  workflow_execution_statuses:
    type: array
    description: |
      Workflow execution statuses of the product (only available when the "with_workflow_execution_statuses" query parameter is set to "true")
    x-immutable: true
    x-read-only: true
    x-from-version: 'SaaS'
    items:
      type: object
      properties:
        uuid:
          type: string
          description: Workflow execution UUID
        status:
          type: string
          description: Status of the workflow execution
          enum: [in_progress, completed]
        started_at:
          type: string
          format: date-time
          description: Date and time when the workflow execution was started
        completed_at:
          type: [string, "null"]
          format: date-time
          description: Date and time when the workflow execution was completed, null if still in progress
        workflow:
          type: object
          properties:
            uuid:
              type: string
              description: Workflow UUID
            code:
              type: string
              description: Workflow code
            labels:
              type: object
              description: Workflow labels for each locale
              additionalProperties:
                type: string
        tasks:
          type: array
          description: Tasks associated with the workflow execution
          items:
            type: object
            properties:
              uuid:
                type: string
                description: Task UUID
              status:
                type: string
                description: Status of the task
                enum: [in_progress]
              created_at:
                type: string
                format: date-time
                description: Date and time when the task was created
              step:
                type: object
                properties:
                  uuid:
                    type: string
                    description: Step UUID
                  code:
                    type: string
                    description: Step code
                  labels:
                    type: object
                    description: Step labels for each locale
                    additionalProperties:
                      type: string

example: {
  "code": "model-biker-jacket-leather",
  "family": "clothing",
  "family_variant": "clothing_material_size",
  "parent": "model-biker-jacket",
  "categories": ["summer_collection"],
  "values": {
    "color": [
      {
        "locale": null,
        "scope": null,
        "data": "antique_white"
      }
    ],
    "material": [
      {
        "locale": null,
        "scope": null,
        "data": "leather"
      }
    ],
    "variation_name": [
      {
        "locale": "en_US",
        "scope": null,
        "data": "Biker jacket leather"
      }
    ],
    "name": [
      {
        "locale": "en_US",
        "scope": null,
        "data": "Biker jacket"
      }
    ],
    "collection": [
      {
        "locale": null,
        "scope": null,
        "data": ["summer_2017"]
      }
    ],
    "description": [
      {
        "locale": "en_US",
        "scope": "ecommerce",
        "data": "Biker jacket"
      }
    ]
  },
  "associations": {
    "PACK": {
      "products": ["sunglass"],
      "product_models": [],
      "groups": []
    }
  },
  "quantified_associations": {
    "PRODUCT_SET": {
      "products": [
        {
          "identifier": "top",
          "quantity": 2
        },
        {
          "identifier": "cap",
          "quantity": 1
        }
      ],
      "product_models": [
        {
          "code": "model-biker-jacket-leather",
          "quantity": 2
        }
      ]
    }
  },
  "quality_scores": [
    {
      "scope": "ecommerce",
      "locale": "en_US",
      "data": "A"
    },
    {
      "scope": "ecommerce",
      "locale": "fr_FR",
      "data": "B"
    },
    {
      "scope": "tablet",
      "locale": "en_US",
      "data": "D"
    },
    {
      "scope": "tablet",
      "locale": "fr_FR",
      "data": "E"
    }
  ],
  "workflow_execution_statuses": [
    {
      "uuid": "8c0fe59f-4d29-4faa-b4c3-d327e7f3cc52",
      "status": "in_progress",
      "started_at": "2024-02-22T17:31:00Z",
      "completed_at": null,
      "workflow": {
        "uuid": "6f37476a-04c2-46c0-b6d0-e18316959068",
        "code": "enrichment_workflow",
        "labels": {
          "en_US": "Enrichment workflow",
          "fr_FR": "Workflow d'enrichissement"
        }
      },
      "tasks": [
        {
          "uuid": "8f6c2d18-fbd4-4f7e-81df-cb3dc368fe07",
          "status": "in_progress",
          "created_at": "2024-02-22T17:31:00Z",
          "step": {
            "uuid": "f626d0e5-84a5-41fc-8215-65508c253edb",
            "code": "review_step",
            "labels": {
              "en_US": "Marketing review",
              "fr_FR": "Revue marketing"
            }
          }
        }
      ]
    },
    {
      "uuid": "59169984-6d6c-4fa7-b925-68b8e9d31ddb",
      "status": "completed",
      "started_at": "2024-02-22T17:31:00Z",
      "completed_at": "2024-02-22T17:31:00Z",
      "workflow": {
        "uuid": "b69ee158-a421-4680-bec0-a71bc73b8e31",
        "code": "compliance_workflow",
        "labels": {}
      },
      "tasks": []
    }
  ],
  "created": "2017-10-02T15:03:55+02:00",
  "updated": "2017-10-02T15:03:55+02:00"
}
