type: object
required: ["code", "family_variant"]
properties:
  code:
    type: string
    description: Product model code
    x-immutable: true
  family:
    type: string
    description: Family code  from which the product inherits its attributes and attributes requirements (since the 3.2)
    x-validation-rules: It is equal to an existing family code
    x-immutable: true
  family_variant:
    type: string
    description: Family variant code from which the product model inherits its attributes and variant attributes
    x-validation-rules: It is equal to an existing family variant code that belong to the family given in the `family` field
    x-immutable: true
  parent:
    type: string
    description: Code of the parent product model. This parent can be modified since the 2.3.
    x-validation-rules: "&bull; It is equal to an existing product model code&#10;&bull; This product model has the same family variant as the one given in the `family_variant field`"
    default: "null"
  categories:
    type: array
    description: Codes of the categories in which the product model is categorized
    x-validation-rules: Each string of the array is equal to an existing category code
    items:
      type: string
    default: []
  values:
    type: object
    description: "Product model attributes values, see <a href='/concepts/products.html#focus-on-the-products-values'>Product values</a> section for more details"
    x-validation-rules: Validation rules detailed in Product values section
    properties:
      attributeCode:
        type: array
        items:
          type: object
          properties:
            scope:
              type: string
              description: Channel code of the product value
            locale:
              type: string
              description: Locale code of the product value
            data:
              type: object
              description: Product value
  quantified_associations:
    type: object
    description: Several quantified associations related to products and/or product models, grouped by quantified association types (only available in Serenity)
    x-validation-rules: "&bull; The `quantifiedAssociationTypeCode` is the code of an existing association type which provides quantity information. &#10;&bull; Each object in the array of the property `products` contains the identifier of an existing product and the quantity of it. &#10;&bull; Each object in the array of the property `product_models` contains the code of an existing product model and the quantity of it. &#10;&bull; Identifiers used in the object collection of the property `product_models` cannot be equal to the product model code."
    properties:
      quantifiedAssociationTypeCode:
        type: object
        properties:
          products:
            type: array
            description: Array of objects containing product identifiers and quantities with which the product is in relation
            items:
              type: object
              properties:
                identifier:
                  type: string
                quantity:
                  type: string
          product_models:
            type: array
            description: Array of objects containing product model codes and quantities with which the product is in relation
            items:
              type: object
              properties:
                code:
                  type: string
                quantity:
                  type: string
  created:
    type: string
    description: Date of creation
    format: dateTime
    x-immutable: true
    x-read-only: true
  updated:
    type: string
    description: Date of the last update
    format: dateTime
    x-read-only: true
  metadata:
    type: object
    description: More information around the product model (only available since the v2.3 in the Enterprise Edition)
    x-immutable: true
    x-read-only: true
    properties:
      workflow_status:
        description: Status of the product model regarding the user permissions (only available since the v2.3 in the Enterprise Edition)
        type: string
        enum: ['read_only','draft_in_progress','proposal_waiting_for_approval','working_copy']

example: {
  "code": "model-biker-jacket-leather",
  "family": "clothing",
  "family_variant": "clothing_material_size",
  "parent": "model-biker-jacket",
  "categories": ["summer_collection"],
  "values": {
    "color": [
      {
        "locale": null,
        "scope": null,
        "data": "antique_white"
      }
    ],
    "material": [
      {
        "locale": null,
        "scope": null,
        "data": "leather"
      }
    ],
    "variation_name": [
      {
        "locale": "en_US",
        "scope": null,
        "data": "Biker jacket leather"
      }
    ],
    "name": [
      {
        "locale": "en_US",
        "scope": null,
        "data": "Biker jacket"
      }
    ],
    "collection": [
      {
        "locale": null,
        "scope": null,
        "data": ["summer_2017"]
      }
    ],
    "description": [
      {
        "locale": "en_US",
        "scope": "ecommerce",
        "data": "Biker jacket"
      }
    ]
  },,
  "quantified_associations": {
    "PACK": {
      "products": [
      {
        "identifier": "top",
        "quantity": 2
      },
      {
        "identifier": "cap",
        "quantity": 1
      }
      ],
      "product_models": [
      {
        "code": "model-biker-jacket-leather",
        "quantity": 2
      }
      ]
    },
    "PROMO": {
      "products": [],
      "product_models": []
    }
  },
  "created": "2017-10-02T15:03:55+02:00",
  "updated": "2017-10-02T15:03:55+02:00"
}
